seed: 42
results_dir: "./results_task1"
save_curves: "./results_task2"

router_servers: ["MinRouterServer", "MaxRouterServer", "RandomRouterServer"]
compared_to_router_server: "OracleRouterServer"

report_to: ["stdio", "txt"]